import pygame as pg

BUTTONS_MENU_CLOSE = [pg.K_ESCAPE]
BUTTONS_MENU_OPEN = [pg.K_ESCAPE]

BUTTONS_MENU_UP = [pg.K_UP]
BUTTONS_MENU_DOWN = [pg.K_DOWN]
BUTTONS_MENU_LEFT = [pg.K_LEFT]
BUTTONS_MENU_RIGHT = [pg.K_RIGHT]

BUTTONS_MENU_CONFIRM = [pg.K_RETURN]
BUTTONS_MENU_DENY = [pg.K_SPACE]

BUTTONS_MOVE_LEFT = [pg.K_LEFT]
BUTTONS_MOVE_RIGHT = [pg.K_RIGHT, pg.K_RETURN]
BUTTONS_JUMP = [pg.K_UP, pg.K_SPACE]

SERIAL_BUTTON_R = pg.K_RETURN
SERIAL_BUTTON_Y = pg.K_SPACE
SERIAL_BUTTON_START = pg.K_ESCAPE
SERIAL_BUTTON_SELECT = pg.K_BACKSPACE # unused?
SERIAL_BUTTON_UP = pg.K_UP
SERIAL_BUTTON_DOWN = pg.K_DOWN
SERIAL_BUTTON_LEFT = pg.K_LEFT
SERIAL_BUTTON_RIGHT = pg.K_RIGHT