import pygame as pg

BUTTONS_MENU_CLOSE = [pg.K_ESCAPE]
BUTTONS_MENU_OPEN = [pg.K_ESCAPE, pg.K_F1]

BUTTONS_MENU_UP = [pg.K_UP]
BUTTONS_MENU_DOWN = [pg.K_DOWN]
BUTTONS_MENU_LEFT = [pg.K_LEFT]
BUTTONS_MENU_RIGHT = [pg.K_RIGHT]

BUTTONS_MENU_CONFIRM = [pg.K_RETURN]
BUTTONS_MENU_DENY = [pg.K_SPACE]

BUTTONS_MOVE_LEFT = [pg.K_LEFT]
BUTTONS_MOVE_RIGHT = [pg.K_RIGHT, pg.K_RETURN]
BUTTONS_JUMP = [pg.K_UP, pg.K_SPACE]

BUTTONS_HIGHSCORE_PAGE_DOWN = [pg.K_PAGEDOWN, pg.K_EQUALS, pg.K_KP_PLUS]
BUTTONS_HIGHSCORE_PAGE_UP = [pg.K_PAGEUP, pg.K_MINUS, pg.K_KP_MINUS]

BUTTONS_LOAD_RECORDING_1 = [pg.K_1, pg.K_KP1]
BUTTONS_LOAD_RECORDING_2 = [pg.K_2, pg.K_KP2]
BUTTONS_LOAD_RECORDING_3 = [pg.K_3, pg.K_KP3]
BUTTONS_LOAD_RECORDING_4 = [pg.K_4, pg.K_KP4]
BUTTONS_LOAD_RECORDING_5 = [pg.K_5, pg.K_KP5]
BUTTONS_LOAD_RECORDING_6 = [pg.K_6, pg.K_KP6]
BUTTONS_LOAD_RECORDING_7 = [pg.K_7, pg.K_KP7]
BUTTONS_LOAD_RECORDING_8 = [pg.K_8, pg.K_KP8]
BUTTONS_LOAD_RECORDING_9 = [pg.K_9, pg.K_KP9]
BUTTONS_LOAD_RECORDING_10 = [pg.K_0, pg.K_KP0]
BUTTONS_LOAD_RECORDING = (BUTTONS_LOAD_RECORDING_1 + BUTTONS_LOAD_RECORDING_2 + BUTTONS_LOAD_RECORDING_3 +
                          BUTTONS_LOAD_RECORDING_4 + BUTTONS_LOAD_RECORDING_5 + BUTTONS_LOAD_RECORDING_6 +
                          BUTTONS_LOAD_RECORDING_7 + BUTTONS_LOAD_RECORDING_8 + BUTTONS_LOAD_RECORDING_9 +
                          BUTTONS_LOAD_RECORDING_10)

SERIAL_BUTTON_R = pg.K_RETURN
SERIAL_BUTTON_Y = pg.K_SPACE
SERIAL_BUTTON_START = pg.K_INSERT
SERIAL_BUTTON_SELECT = pg.K_BACKSPACE # unused?
SERIAL_BUTTON_UP = pg.K_UP
SERIAL_BUTTON_DOWN = pg.K_DOWN
SERIAL_BUTTON_LEFT = pg.K_LEFT
SERIAL_BUTTON_RIGHT = pg.K_RIGHT
SERIAL_CONTROLLER_DC = pg.K_BREAK
SERIAL_CONTROLLER_CN = pg.K_ESCAPE